CREATE TABLE employees_history (
    id SERIAL PRIMARY KEY,
    is_active_arkus BOOLEAN,
    is_active_mind BOOLEAN,
    full_name VARCHAR(255) NOT NULL,
    role VARCHAR(50),
    level VARCHAR(50),
    cv_link TEXT,
    tech_profile_1 VARCHAR(100),
    entry_type VARCHAR(100),
    mt_entry_date DATE,
    mt_exit_date DATE,
    business_days_in_mt INTEGER,
    office_location VARCHAR(100),
    city_of_residence VARCHAR(100),
    time_zone VARCHAR(50),
    assigned_account_or_clients VARCHAR(255),
    english_level VARCHAR(50),
    mt_exit_projection_date DATE,
    base_income_money NUMERIC,
    tech_profile_2 VARCHAR(100),
    mt_validated TEXT,
    company_exit_type VARCHAR(100),
    company_exit_date DATE,
    entry_type_details TEXT
);
INSERT INTO employees_history (is_active_arkus, is_active_mind, full_name, role, level, cv_link, tech_profile_1,entry_type, mt_entry_date, mt_exit_date, business_days_in_mt, office_location,city_of_residence, time_zone, assigned_account_or_clients, english_level, mt_exit_projection_date, base_income_money, tech_profile_2, mt_validated, company_exit_type, company_exit_date, entry_type_details) VALUES 
 (FALSE, TRUE, 'Alice Johnson', 'Developer', 'Mid', 'http://example.com/cv/alice', 
 'JavaScript', 'Internal Transfer', '2023-01-10', NULL, 220, 'HQ', 'New York', 'EST', 
 'Client A', 'C1', NULL, 50000.00, 'React', 'Yes', NULL, NULL, NULL),
 (TRUE, FALSE, 'Bob Smith', 'Product Manager', 'Senior', 'http://example.com/cv/bob', 
 'Product Management', 'External Hire', '2022-06-15', NULL, 400, 'HQ', 'Chicago', 'CST', 
 'Client B', 'B2', NULL, 75000.00, 'Agile Methodologies', 'Yes', NULL, NULL, NULL),
 (FALSE, TRUE, 'Carol Davis', 'Scrum Master', 'Mid', 'http://example.com/cv/carol', 
 'Scrum', 'Internal Transfer', '2023-03-01', '2023-12-31', 200, 'Remote', 'Denver', 'MST', 
 'Client C', 'B1', '2023-12-31', 60000.00, 'Kanban', 'Yes', 'Resignation', '2023-12-31', 
 'Moved to another team'),
 (TRUE, FALSE, 'David Wilson', 'Data Analyst', 'Junior', 'http://example.com/cv/david', 
 'SQL', 'External Hire', '2022-08-01', NULL, 350, 'Remote', 'Seattle', 'PST', 
 'Internal', 'C1', NULL, 45000.00, 'Power BI', 'No', NULL, NULL, NULL),
 (FALSE, TRUE, 'Emily Martinez', 'Backend Developer', 'Senior', 'http://example.com/cv/emily', 
 'Node.js', 'Internal Transfer', '2021-11-20', '2024-01-15', 700, 'Remote', 'Austin', 
 'CST', 'Client D', 'C2', '2024-01-15', 80000.00, 'Docker', 'Yes', 'Termination', 
 '2024-01-15', 'Performance issues'),
 (TRUE, FALSE, 'Frank Thomas', 'Frontend Developer', 'Mid', 'http://example.com/cv/frank', 
 'Vue.js', 'External Hire', '2023-05-10', NULL, 150, 'Remote', 'San Francisco', 'PST', 
 'Client E', 'B2', NULL, 65000.00, 'CSS', 'No', NULL, NULL, NULL),
 (FALSE, TRUE, 'Grace Lewis', 'System Admin', 'Senior', 'http://example.com/cv/grace', 
 'Linux', 'Internal Transfer', '2020-01-01', '2023-06-30', 850, 'HQ', 'Miami', 'EST', 
 'Internal', 'C1', '2023-06-30', 70000.00, 'Networking', 'Yes', 'Retirement', 
 '2023-06-30', 'Age limit'),
 (TRUE, TRUE, 'Harry Walker', 'DevOps Engineer', 'Junior', 'http://example.com/cv/harry', 
 'AWS', 'External Hire', '2023-07-20', NULL, 120, 'Remote', 'Dallas', 'CST', 
 'Client F', 'C2', NULL, 55000.00, 'Terraform', 'Yes', NULL, NULL, NULL),
 (FALSE, FALSE, 'Isla Scott', 'QA Engineer', 'Mid', 'http://example.com/cv/isla', 
 'Testing', 'External Hire', '2019-09-15', '2023-09-14', 1000, 'HQ', 'Atlanta', 'EST', 
 'Client G', 'C1', '2023-09-14', 60000.00, 'Selenium', 'No', 'End of Contract', 
 '2023-09-14', 'Fixed-term contract end'),
 (TRUE, TRUE, 'Jack Carter', 'Tech Lead', 'Senior', 'http://example.com/cv/jack', 
 'Python', 'Internal Promotion', '2021-02-01', NULL, 900, 'Remote', 'Houston', 'CST', 
 'Client H', 'B2', NULL, 95000.00, 'Flask', 'Yes', NULL, NULL, NULL),
 (FALSE, TRUE, 'Karen Turner', 'Designer', 'Junior', 'http://example.com/cv/karen', 
 'UI/UX', 'External Hire', '2022-03-12', '2023-03-11', 240, 'Remote', 'Boston', 'EST', 
 'Client I', 'B1', '2023-03-11', 40000.00, 'Figma', 'Yes', 'Resignation', '2023-03-11', 
 'Personal reasons'),
 (TRUE, FALSE, 'Liam Anderson', 'Full Stack Developer', 'Senior', 
 'http://example.com/cv/liam', 'JavaScript', 'External Hire', '2022-11-01', NULL, 260, 
 'HQ', 'San Diego', 'PST', 'Client J', 'C1', NULL, 85000.00, 'Node.js', 'No', NULL, NULL, NULL),
 (FALSE, TRUE, 'Mia Ramirez', 'Backend Developer', 'Mid', 'http://example.com/cv/mia', 
 'Java', 'Internal Transfer', '2023-02-15', '2024-02-14', 240, 'HQ', 'Tampa', 'EST', 
 'Client K', 'C2', '2024-02-14', 70000.00, 'Spring Boot', 'Yes', 'Termination', 
 '2024-02-14', 'Client budget cut'),
 (TRUE, FALSE, 'Noah Rivera', 'Network Engineer', 'Senior', 'http://example.com/cv/noah', 
 'Cisco', 'External Hire', '2023-04-10', NULL, 180, 'Remote', 'Orlando', 'EST', 
 'Internal', 'B2', NULL, 75000.00, 'Firewall', 'Yes', NULL, NULL, NULL),
 (FALSE, TRUE, 'Olivia Hughes', 'Security Analyst', 'Junior', 'http://example.com/cv/olivia', 
 'Cybersecurity', 'Internal Promotion', '2022-12-01', '2024-01-01', 280, 'Remote', 
 'Phoenix', 'MST', 'Client L', 'C1', '2024-01-01', 55000.00, 'Penetration Testing', 'No', 
 'Resignation', '2024-01-01', 'Relocation'),
 (TRUE, FALSE, 'Paul Baker', 'Database Admin', 'Mid', 'http://example.com/cv/paul', 
 'PostgreSQL', 'External Hire', '2023-09-15', NULL, 90, 'Remote', 'Detroit', 'EST', 
 'Client M', 'B2', NULL, 65000.00, 'MongoDB', 'Yes', NULL, NULL, NULL),
 (FALSE, TRUE, 'Quinn Green', 'Mobile Developer', 'Senior', 'http://example.com/cv/quinn', 
 'Swift', 'Internal Transfer', '2021-10-01', '2023-12-31', 600, 'HQ', 'Portland', 'PST', 
 'Client N', 'C2', '2023-12-31', 90000.00, 'Kotlin', 'Yes', 'Retirement', '2023-12-31', 
 'Age limit'),
 (TRUE, FALSE, 'Ruby Adams', 'Support Specialist', 'Junior', 'http://example.com/cv/ruby', 
 'IT Support', 'External Hire', '2023-08-01', NULL, 120, 'Remote', 'Salt Lake City', 
 'MST', 'Client O', 'B1', NULL, 45000.00, 'Helpdesk', 'No', NULL, NULL, NULL),
 (FALSE, TRUE, 'Steve Carter', 'QA Tester', 'Mid', 'http://example.com/cv/steve', 
 'Testing', 'Internal Promotion', '2022-01-01', '2023-05-31', 400, 'Remote', 
 'Nashville', 'CST', 'Client P', 'C2', '2023-05-31', 50000.00, 'JUnit', 'Yes', 
 'Termination', '2023-05-31', 'Project ended'),
 (TRUE, TRUE, 'Tina Long', 'Tech Support', 'Junior', 'http://example.com/cv/tina', 
 'IT Support', 'External Hire', '2023-06-10', NULL, 140, 'HQ', 'Las Vegas', 'PST', 
 'Client Q', 'B1', NULL, 40000.00, 'Helpdesk', 'Yes', NULL, NULL, NULL);


-- CREATE TABLE users (
--     id SERIAL PRIMARY KEY,
--     name VARCHAR(255),
--     email VARCHAR(255) NOT NULL UNIQUE,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- INSERT INTO users(name, email) 
--     VALUES ('Eduardo RS', 'erendon@arkusnexus.com'), 
--     ('Gael Felix', 'gfelix@arkusnexus.com'), 
--     ('Eduardo de Anda', 'edeanda@arkusnexus.com'), 
--     ('Alvaro Munoz', 'amunoz@arkusnexus.com'), 
--     ('Fernanda Gonzalez', 'mgonzalez@arkusnexus.com');

